spring:
  profiles:
    active:
      development
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: pokedex2012
    password: pokedex

---

spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/pokedex2012
